# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
       ohmyzsh: "git@github.com:RandellP/puppet-ohmyzsh.git"
  forge_modules:
     stdlib: "puppetlabs/stdlib"
     sudo: "saz-sudo"
     tmux: "zanloy-tmux"
     git: "rehan-git"
     rbenv: "jdowning-rbenv"
     java: "puppetlabs-java"
     vcsrepo: "puppetlabs-vcsrepo"
     wget: "rehan-wget"
     nginx: "puppet-nginx"
     pdk: "abuxton-pdk"
     archive: "puppet-archive"
     yumrepo_code: "puppetlabs/yumrepo_core"
