mod 'abuxton-pdk'
mod 'chocolatey-chocolatey'
mod 'crayfishx-firewalld'
mod 'jdowning-rbenv'
mod 'puppet-archive', '3.2.0'
mod 'puppet-grafana', '6.1.0'
mod 'puppet-nginx'
mod 'puppet-selinux'
mod 'puppet-windows_env'
mod 'puppetlabs-apt'
mod 'puppetlabs-concat'
mod 'puppetlabs-inifile'
mod 'puppetlabs-java'
mod 'puppetlabs-ntp'
mod 'puppetlabs-puppet_metrics_dashboard'
mod 'puppetlabs-powershell'
mod 'puppetlabs-stdlib', '4.25.1'
mod 'puppetlabs-translate'
mod 'puppetlabs-vcsrepo'
mod 'rehan-git'
mod 'rehan-ohmyzsh'
mod 'rehan-wget'
mod 'stahnma-epel'
mod 'stm-debconf'
mod 'saz-sudo'
mod 'saz-timezone'
mod 'zanloy-tmux'
